---
- name: Install Java Api
  hosts: api
  tags: API
  become: yes
  roles:
    - api

- name: Install Database
  hosts: db
  tags: DB
  become: yes
  roles:
    - db

- name: Install Test Environment
  hosts: test
  tags: TEST
  become: yes
  roles:
    - test
  